#!/usr/bin/env python3

from math import sqrt

'''
Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal and
D = |Pk − Pj| is minimised; what is the value of D?
'''

'''
(3*n^2 - n) + (3*m^2 - m) = 3*j^2 - j
(3*n^2 - n) - (3*m^2 - m) = 3*k^2 - k
'''

def is_pentagonal(num):
    return (1 + sqrt(1 + 12*num))/6

def pent(num):
    return 3*num*num - num

i = 0
while True:
    i += 1

    for j in range(1, i):
        n = is_pentagonal(pent(i)+pent(j))

        if n.is_integer():
            m = is_pentagonal(pent(i)+2*pent(j))
            if m.is_integer():
                print('Winner: {}'.format(pent(i)/2))
                quit()



