#!/usr/bin/env python3

from math import sqrt

'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def is_pentagonal(n):
    return ((1 + sqrt(1+24*n))/6).is_integer()

def is_hexagonal(n):
    return ((1 + sqrt(1+8*n))/4).is_integer()

def tri(n):
    return (n**2 + n)/2

i = 285
while True:
    i += 1

    tri_i = tri(i)

    if is_pentagonal(tri_i) and is_hexagonal(tri_i):
        print('Winner: {}'.format(tri_i))
        quit()
